// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCz2GeD6dRbQvhUKFYbKauXVJy8sUfQPZo',
    appId: '1:313892608727:web:f17a7b444ae48565c36e92',
    messagingSenderId: '313892608727',
    projectId: 'easyinventory-184c4',
    authDomain: 'easyinventory-184c4.firebaseapp.com',
    storageBucket: 'easyinventory-184c4.firebasestorage.app',
    measurementId: 'G-0R8L6WGEHH',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6cvSNma6oluCuXMvMnvsnvhyBbeODcq4',
    appId: '1:313892608727:ios:f6301cc0f9722155c36e92',
    messagingSenderId: '313892608727',
    projectId: 'easyinventory-184c4',
    storageBucket: 'easyinventory-184c4.firebasestorage.app',
    iosBundleId: 'com.example.easyinventory',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCz2GeD6dRbQvhUKFYbKauXVJy8sUfQPZo',
    appId: '1:313892608727:web:7c1cbf35b66211f2c36e92',
    messagingSenderId: '313892608727',
    projectId: 'easyinventory-184c4',
    authDomain: 'easyinventory-184c4.firebaseapp.com',
    storageBucket: 'easyinventory-184c4.firebasestorage.app',
    measurementId: 'G-L0DGP4W9S7',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6cvSNma6oluCuXMvMnvsnvhyBbeODcq4',
    appId: '1:313892608727:ios:f6301cc0f9722155c36e92',
    messagingSenderId: '313892608727',
    projectId: 'easyinventory-184c4',
    storageBucket: 'easyinventory-184c4.firebasestorage.app',
    iosBundleId: 'com.example.easyinventory',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACehslD7ZUS3b85IOm8LMtIJajeODhpKg',
    appId: '1:313892608727:android:5f4e38fce01d4a47c36e92',
    messagingSenderId: '313892608727',
    projectId: 'easyinventory-184c4',
    storageBucket: 'easyinventory-184c4.firebasestorage.app',
  );

}